version: '3.5'

x-logging: &default-logging
  options:
    max-size: '50m'
    max-file: '1'
  driver: json-file

services:

  proxy-balancer:
    image: brunneis/anon-proxy-balancer
    ports:
      - 9999:9999
    logging: *default-logging
    tty: true

